Set -e to exit on errors

diff --git a/filer/scripts/hgimport b/filer/scripts/hgimport
--- a/filer/scripts/hgimport
+++ b/filer/scripts/hgimport
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+# Exit on errors
+set -e
+
 # Use Alex's filer alias. This will be removed later.
 filer() { python -m filer1.commands.main "$@"; }
 
@@ -27,6 +30,7 @@ hg log --repository source -r $1 --template "{node}\n" | while read hash; do
         filer checkout --repository target --working w --revision "$filerparent"
     fi
     # Update to the corresponding Mercurial revision
+    rm -r source/*
     hg update --repository source $hash
     # Copy files over
     cp -r source/* w
